
package com.ib.omb.ws.signdoc;

import javax.xml.ws.WebFault;




/**
 * This class was generated by Apache CXF 3.3.3
 * 2020-07-17T13:04:22.143+03:00
 * Generated source version: 3.3.3
 */

@WebFault(name = "WSFault", targetNamespace = "http://wstransfer.delo.indexbg.com/")
public class WSFault extends Exception {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8768894805673794293L;
	String info;
	long errorCode;

	public WSFault(long erroCode,String message, Exception ex) {
		super(message, ex);
		this.setErrorCode(errorCode);
	}
	
	public WSFault(String message, Exception ex) {
		super(message, ex);

	}

	public WSFault(String message) {
		super(message);

	}

	public WSFault(String message, String detail) {
		super(message);
		this.info = detail;
	}
	

	public WsError getFaultInfo() {
		 return new WsError(info,errorCode);
	}

	public long getErrorCode() {
		return errorCode;
	}
	
	public void setErrorCode(long errorCode) {
		this.errorCode = errorCode;
	}
	public String getMessage() {

		return super.getMessage();
	}
}
