
package com.indexbg.omb.reg;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-11-23T11:27:26.103+02:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "DocuServiceFault", targetNamespace = "http://reg.docu.indexbg.com/")
public class DocuServiceFault_Exception extends Exception {
    
    private com.indexbg.omb.reg.DocuServiceFault docuServiceFault;

    public DocuServiceFault_Exception() {
        super();
    }
    
    public DocuServiceFault_Exception(String message) {
        super(message);
    }
    
    public DocuServiceFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public DocuServiceFault_Exception(String message, com.indexbg.omb.reg.DocuServiceFault docuServiceFault) {
        super(message);
        this.docuServiceFault = docuServiceFault;
    }

    public DocuServiceFault_Exception(String message, com.indexbg.omb.reg.DocuServiceFault docuServiceFault, Throwable cause) {
        super(message, cause);
        this.docuServiceFault = docuServiceFault;
    }

    public com.indexbg.omb.reg.DocuServiceFault getFaultInfo() {
        return this.docuServiceFault;
    }
}
