package com.indexbg.omb.reg;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2021-11-23T11:27:26.135+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "DocuService", 
                  wsdlLocation = "http://192.168.0.105:8080/DocuWork/DocuService?wsdl",
                  targetNamespace = "http://reg.docu.indexbg.com/") 
public class DocuService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://reg.docu.indexbg.com/", "DocuService");
    public final static QName DocuServicePort = new QName("http://reg.docu.indexbg.com/", "DocuServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.105:8080/DocuWork/DocuService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocuService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.105:8080/DocuWork/DocuService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocuService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocuService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocuService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DocuService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DocuService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DocuService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DocuServiceSOAP
     */
    @WebEndpoint(name = "DocuServicePort")
    public DocuServiceSOAP getDocuServicePort() {
        return super.getPort(DocuServicePort, DocuServiceSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocuServiceSOAP
     */
    @WebEndpoint(name = "DocuServicePort")
    public DocuServiceSOAP getDocuServicePort(WebServiceFeature... features) {
        return super.getPort(DocuServicePort, DocuServiceSOAP.class, features);
    }

}
